// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20210903095620_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.data.model.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Categoriid");

                    b.Property<int>("avialable");

                    b.Property<int>("categoryid");

                    b.Property<string>("img");

                    b.Property<bool>("isfavorit");

                    b.Property<string>("longdesc");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.Property<string>("shortdesc");

                    b.HasKey("id");

                    b.HasIndex("Categoriid");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("WebApplication1.data.model.Categori", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("desc");

                    b.Property<string>("namecategori");

                    b.HasKey("id");

                    b.ToTable("Categori");
                });

            modelBuilder.Entity("WebApplication1.data.model.Car", b =>
                {
                    b.HasOne("WebApplication1.data.model.Categori", "Categori")
                        .WithMany("cars")
                        .HasForeignKey("Categoriid");
                });
#pragma warning restore 612, 618
        }
    }
}
